package ChatBot.enums;

public enum ConfigName {
    NAM_DB_USER,
    NAM_DB_PASSWORD,
    NAM_DB_IP,
    NAM_DB_PORT,
    NAM_DB_NAME,
    NAM_SOLR_IP,
    NAM_SOLR_PORT,
    NAM_SOLR_CORE,
    NAM_TWITCH_USERNAME,
    NAM_TWITCH_CLIENTID,
    NAM_TWITCH_SECRET,
    NAM_TWITCH_OAUTH,
    NAM_TWITCH_UID,
    NAM_TWITCH_CHANNEL_TO_JOIN,
    NAM_FTP_SERVER,
    NAM_FTP_PORT,
    NAM_FTP_USERNAME,
    NAM_FTP_PASSWORD,
    NAM_BOT_WEBSITE,
    NAM_BOT_ADMIN
}
